dashboard/api/urls.py
from django.urls import path 
from dashboard.api.views.views_profile import ProfileAPIView
 
urlpatterns = [  
    path('profiles/', ProfileAPIView.as_view(), name='profiles'),
    path('profiles/<int:profile_id>/', ProfileAPIView.as_view(), name='profile'),
 
]

dashboard/urls.py
from django.conf.urls.static import static
from django.urls import include, path, re_path as url
 
from getref import settings   
from dashboard.utils import *
    
from django.contrib.auth import views as auth_views 
from dashboard.forms import * 
from dashboard.views.views_accounts import (
    LandingPageView,
    LoginView,
    CustomLoginView,
    ReferralRedirectView, ResetPasswordView, ChangePasswordView, RegisterView
)
from dashboard.views.views_profile import (

    ProfileView, UserProfileDataView,
)
from dashboard.views.views_dashboard import (
    HomeView,
    IncompleteRegistrationsView,
    InvestorAccountsView,
    MasterAccountsView,
    MyIBsView,
    ParticipateCampaignView,
    WithdrawalView,
)
from dashboard.views.views_kit_template import (
    ChartJSView,
    DocumentationView,
    BasicElementsView,
    IconsView,
    Error400View,
    Error404View,
    TableView,
    DropdownsView,
    TypographyView,
)

"""urlpatterns = [
    #path('', home, name='core-home'),
    path('profile/', ProfileView.as_view(), name='core_profile'),
    path('user_profile_data/', UserProfileDataView.as_view(), name='core_user_profile_data'),
    
    path('register/', RegisterView.as_view(), name='core_register'),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='core/login.html',
                                           authentication_form=LoginForm), name='core_login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='core/logout.html'), name='logout'),

    path('password-reset/', ResetPasswordView.as_view(), name='core_password_reset'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='core/core_password_reset_complete.html'),
         name='core_password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='core_password_change'),

    url(r'^oauth/', include('social_django.urls', namespace='social')),

] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)"""


from django.urls import path 
from django.contrib.auth.views import LogoutView

urlpatterns = [
    ## dashboard
    path('', HomeView.as_view(), name='core_home'),
    path('dashboard/', HomeView.as_view(), name='dashboard'),
    path('accounts/master/', MasterAccountsView.as_view(), name='master_accounts'),
    path('accounts/investor/', InvestorAccountsView.as_view(), name='investor_accounts'),
    path('accounts/incomplete/', IncompleteRegistrationsView.as_view(), name='incomplete_registrations'),
    path('my-ibs/', MyIBsView.as_view(), name='my_ibs'),

    # get users referred with level
    #path('get-level-users/', UserReferredLevelView.as_view(), name='get_user_table'), #get_user_table, name='get_user_table'),

    ## accounts
    # Pagina di atterraggio
    path('landing/', LandingPageView.as_view(), name='core_landing_page'),
    
    # Registrazione
    path('register/', RegisterView.as_view(), name='core_register'),    
    path('referral-code/<str:referral_code>/', ReferralRedirectView.as_view(), name='referral_redirect'),
    path('register/<str:referral_code>/', RegisterView.as_view(), name='core_register_with_referral'),
    #path('referral-code/', ReferralRedirectView.as_view(), name='referral_redirect'),
    
    # Login e Logout
    path('login/', CustomLoginView.as_view(), name='core_login'),
    path('accounts/logout/', LogoutView.as_view(next_page='core_home'), name='core_logout'),
    
    # Reset della password
    path('password-reset/', ResetPasswordView.as_view(), name='core_password_reset'),
    
    # Cambio della password
    path('password-change/', ChangePasswordView.as_view(), name='core_change_password'),
    
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html'),
         name='core_password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='core/core_password_reset_complete.html'),
         name='core_password_reset_complete'),

    ## profile
    path('profile/', ProfileView.as_view(), name='core_profile'),
    
    # Dati profilo utente (API JSON)
    path('profile/data/', UserProfileDataView.as_view(), name='core_profile_data'),
    
    # Partecipazione a campagne di referral
    path('campaign/participate/', ParticipateCampaignView.as_view(), name='core_participate_campaign'),
    
    path('withdrawals/', WithdrawalView.as_view(), name='withdrawals'),

    ## kit_template visible only for admin
    path('charts/chartjs/', ChartJSView.as_view(), name='charts'),
    path('documentation/', DocumentationView.as_view(), name='documentation'),
    path('forms/basic_elements/', BasicElementsView.as_view(), name='forms_basic_elements'),
    path('icons/', IconsView.as_view(), name='icons_mdi'),
    path('error/404/', Error400View.as_view(), name='error-404'),
    path('error/500/', Error404View.as_view(), name='error-500'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('tables/basic-table/', TableView.as_view(), name='basic_table'),
    path('ui-features/buttons/', DropdownsView.as_view(), name='ui_features_buttons'),
    path('ui-features/dropdowns/', DropdownsView.as_view(), name='ui_features_dropdowns'),
    path('ui-features/typography/', TypographyView.as_view(), name='ui_features_typography'),
    
    ## api
    path('api/v0/', include('dashboard.api.urls'), name='api_profile'),

    ## social django
    url(r'^oauth/', include('social_django.urls', namespace='social')),

]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

"""urlpatterns = [
    path('', HomeView.as_view(), name='core_home'),
    
    path('', home, name='home'), 
    path('home/', home, name='home'), 
    path('pages/charts/chartjs/', charts_chartjs, name='charts'), 
    path('documentation/', documentation, name='documentation'), 
    path('pages/forms/basic_elements/', forms_basic_elements, name='forms_basic_elements'), 
    path('icons_mdi/', icons_mdi, name='icons_mdi'), 
    path('error_404/', error_404, name='error-404'), 
    path('error_500/', error_500, name='error-500'), 
    #path('login/', login, name='login'), 
    #path('register/', register, name='register'), 
    path('tables_basic_table/', tables_basic_table, name='basic_table'), 
    path('pages/ui-features/buttons/', ui_features_buttons, name='ui_features_buttons'), 
    path('pages/ui-features/dropdowns/', ui_dropdowns, name='ui_features_dropdowns'), 
    path('pages/ui-features/typography/', ui_features_typography, name='ui_features_typography'), 

] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
"""

getref/urls.py
from django.contrib.auth.models import User, Group
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path, re_path as url 
from affiliate.views.views_home import index_view
from getref import settings

#schema_view = get_swagger_view(title='Pastebin API')
from rest_framework import generics, permissions, serializers

from oauth2_provider import urls as oauth2_urls
from oauth2_provider.contrib.rest_framework import TokenHasReadWriteScope, TokenHasScope


from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Get Call API",
        default_version='v1',
        description="Get Call is a web-server RESTful ",
        terms_of_service="https://www.google.com/policies/terms/",
        #contact=openapi.Contact(email="contact@local.local"),
        contact=openapi.Contact(email="alessandro.chiaiese@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
 
urlpatterns = [
    # admin
    path('admin/', admin.site.urls),
    
    # accounts 
    path('', include('accounts.urls')),
    # apps   
    path('', include('dashboard.urls')),
    path('', include('affiliate.urls')),
    path('', include('referral.urls')), 
    #path('', include('subscriptions.urls')), 
    
    #path('/', index_view, name='home'),
    #path('home/', index_view, name='home2'),
    
    # stripe
    path('', include('payments.urls')),
    
    # health
    path('health/', include('health_check.urls')),
    
    # swagger
    #path('api/documentation/', schema_view),
    #url(r'^api/v0/$', schema_view), 
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),


]  + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)


# Media Assets
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models/user.py
from django.db import models

from django.contrib.auth import get_user_model

DjangoUser = get_user_model()

class User(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.OneToOneField(DjangoUser, on_delete=models.CASCADE, related_name="django_user")
    email = models.CharField(max_length=256)
    phone = models.CharField(max_length=256)
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    password = models.CharField(max_length=256)
    roles = models.ManyToManyField('Role', related_name='roles')
    date_created = models.DateField(auto_now=True)
    date_modified = models.DateField(auto_now=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def to_dict(self):
        return {
            'id': self.id,
            'email': self.email,
            'phone': self.phone,
            'first_name': self.first_name,
            'last_name': self.last_name,
            'password': self.password,
            'roles': self.roles,
            'date_created': self.date_created,
            'date_modified': self.date_modified
        }

    class Meta:
        db_table = 'Users'

dashboard/models/country.py
from django.db import models

class Country(models.Model):
    name = models.CharField(max_length=256)

    class Meta:
        verbose_name = "Country"
        verbose_name_plural = "Countries" 

dashboard/models/profile.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

from referral.models.referral_transaction import ReferralTransaction
import payments
from payments.models.payment_method import PaymentMethod

#User(username, first_name, last_name, email, is_staff, is_active, date_joined)

# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    # User: username, first_name, last_name, email, is_staff, is_active, date_joined
    user = models.OneToOneField(User, on_delete=models.CASCADE) 
    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    bio = models.TextField(max_length=1024, null=True, blank=True)

    # base data profile
    birth_date = models.DateTimeField(null=True, blank=True)
    city = models.CharField(max_length=64, null=True, blank=True)
    street = models.CharField(max_length=64, null=True, blank=True)
    CAP = models.CharField(max_length=64, null=True, blank=True)
    phone_number = models.CharField(max_length=13, blank=True, null=True, unique=True)


    # Differenet kind of profile (Business, Buyer, Base)
    is_business = models.BooleanField(default=False)
    is_buyer = models.BooleanField(default=False)
    
    # business
    name_business = models.CharField(max_length=64, blank=True, null=True) # nome azienda
    is_owner = models.BooleanField(default=False)
    user_ower = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE, related_name="owner_business")
    iva = models.CharField(max_length=32, default="0000")
    office_number = models.CharField(max_length=13, blank=True, null=True, unique=True) 
    
    
    # buyer
    transactions = models.ManyToManyField(ReferralTransaction, related_name='txns')
    payment_method = models.OneToOneField(PaymentMethod, blank=True, null=True, on_delete=models.CASCADE, related_name='payment')


    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

dashboard/models/region.py
from django.db import models

class Region(models.Model):
    country = models.OneToOneField('Country', on_delete=models.CASCADE, related_name='region_country')
    name = models.CharField(max_length=256)

    class Meta:
        verbose_name = "Region"
        verbose_name_plural = "Regions" 

dashboard/views/views_kit_template.py
from django.views.generic import TemplateView


#####################
#  ADMIN TEMPLATES  #
#####################
class ChartJSView(TemplateView):
    template_name = 'dashboard/pages/charts/chartjs.html'

class DocumentationView(TemplateView):
    template_name = 'dashboard/pages/documentation/documentation.html'

class BasicElementsView(TemplateView):
    template_name = 'dashboard/pages/forms/basic_elements.html'

class IconsView(TemplateView):
    template_name = 'dashboard/pages/icons/mdi.html'

class Error400View(TemplateView):
    template_name = 'dashboard/pages/samples/error-400.html'

class Error404View(TemplateView):
    template_name = 'dashboard/pages/samples/error-404.html'

class LoginView(TemplateView):
    template_name = 'dashboard/pages/samples/login.html'

class RegisterView(TemplateView):
    template_name = 'dashboard/pages/samples/register.html'

class TableView(TemplateView):
    template_name = 'dashboard/pages/tables/basic-table.html'

class ButtonsView(TemplateView):
    template_name = 'dashboard/pages/ui-features/buttons.html'

class DropdownsView(TemplateView):
    template_name = 'dashboard/pages/ui-features/dropdowns.html'

class TypographyView(TemplateView):
    template_name = 'dashboard/pages/ui-features/typography.html'

"""

def home(request):
    return render(request, 'dashboard/index.html')

def charts_chartjs(request):
    return render(request, 'dashboard/pages/charts/chartjs.html')

def documentation(request):
    return render(request, 'dashboard/pages/documentation/documentation.html')

def forms_basic_elements(request):
    return render(request, 'dashboard/pages/forms/basic_elements.html')

def icons_mdi(request):
    return render(request, 'dashboard/pages/icons/mdi.html')

def error_404(request):
    return render(request, 'dashboard/pages/samples/error-404.html')

def error_500(request):
    return render(request, 'dashboard/pages/samples/error-404.html')

def login(request):
    return render(request, 'dashboard/pages/samples/login.html')

def register(request):
    return render(request, 'dashboard/pages/samples/register.html')

def tables_basic_table(request):
    return render(request, 'dashboard/pages/tables/basic-table.html')

def ui_features_buttons(request):
    return render(request, 'dashboard/pages/ui-features/buttons.html')

def ui_dropdowns(request):
    return render(request, 'dashboard/pages/ui-features/dropdowns.html')

def ui_features_typography(request):
    return render(request, 'dashboard/pages/ui-features/typography.html')

"""

dashboard/templates/core/logout.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Logout{% endblock title %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">You have been logged out</h5>
        <p class="card-text">
            Thanks for your time, contact me for any comments or suggestions using my email address.
        </p>
        <br><hr><a href="{% url 'core_login' %}" class="btn btn-primary">Sign in again</a>
        </div>
    </div>


{% endblock %}

dashboard/templates/core/password_reset.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}Forgot Password{% endblock %}

{% block styles %}
<!-- plugins:css -->
<link rel="stylesheet" href="{% static 'dashboard/vendors/feather/feather.css' %}">
<link rel="stylesheet" href="{% static 'dashboard/vendors/ti-icons/css/themify-icons.css' %}">
<link rel="stylesheet" href="{% static 'dashboard/vendors/css/vendor.bundle.base.css' %}">
<!-- inject:css -->
<link rel="stylesheet" href="{% static 'dashboard/css/vertical-layout-light/style.css' %}">
<!-- endinject -->
<link rel="shortcut icon" href="{% static 'dashboard/images/favicon.png' %}" />
{% endblock %}

{% block content %}
<div class="container-fluid page-body-wrapper full-page-wrapper">
  <div class="content-wrapper d-flex align-items-center auth px-0">
    <div class="row w-100 mx-0">
      <div class="col-lg-4 mx-auto">
        <div class="auth-form-light text-left py-5 px-4 px-sm-5">
          <div class="brand-logo">
            <img src="{% static 'dashboard/images/logo.png' %}" alt="logo">
          </div>
          <h4>Forgot your password?</h4>
          <h6 class="font-weight-light">Enter your email address to reset your password.</h6>

          <!-- Gestione errori del form -->
          {% if form.errors %}
          <div class="alert alert-danger alert-dismissible" role="alert">
              <div id="form_errors">
                  {% for key, value in form.errors.items %}
                      <strong>{{ value }}</strong>
                  {% endfor %}
              </div>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          {% endif %}

          <form method="POST" class="pt-3">
            {% csrf_token %}
            <!-- Campo Email -->
            <div class="form-row">
              <div class="col-md-10 offset-md-1">
                <div class="form-group">
                  <label class="small mb-1" for="id_email">Email</label>
                  <input type="email" name="email" class="form-control form-control-lg"
                         autocomplete="email" maxlength="254" required id="id_email" placeholder="Enter email">
                </div>
              </div>
            </div>

            <!-- Pulsante di invio -->
            <div class="form-row">
              <div class="col-md-10 offset-md-1">
                <div class="form-group mt-0 mb-1">
                  <button type="submit" class="col-md-12 btn btn-dark">Submit</button>
                </div>
              </div>
            </div>
          </form>
        </div>
        <div class="card-footer text-center">
          <div class="small">
            <a href="{% url 'core_register' %}">Create A New Account</a><br><br>
            <a href="{% url 'core_login' %}">Back To Login</a><br>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<!-- plugins:js -->
<script src="{% static 'dashboard/vendors/js/vendor.bundle.base.js' %}"></script>
<!-- inject:js -->
<script src="{% static 'dashboard/js/off-canvas.js' %}"></script>
<script src="{% static 'dashboard/js/hoverable-collapse.js' %}"></script>
<script src="{% static 'dashboard/js/template.js' %}"></script>
<script src="{% static 'dashboard/js/settings.js' %}"></script>
<script src="{% static 'dashboard/js/todolist.js' %}"></script>
{% endblock %}

dashboard/templates/core/password_reset_complete.html
{% extends "core/base.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'core_login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/core/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'core_password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}

dashboard/templates/core/profile.html
{% extends "dashboard/layout.html" %}

{% load static %}

{% block title %}Pagina Profilo - {{ user.first_name }}{% endblock %}

{% block styles %}
<!-- Aggiungere link a librerie CSS -->
<link rel="stylesheet" href="{% static 'dashboard/vendors/feather/feather.css' %}">
<link rel="stylesheet" href="{% static 'dashboard/vendors/ti-icons/css/themify-icons.css' %}">
<link rel="stylesheet" href="{% static 'dashboard/vendors/css/vendor.bundle.base.css' %}">
<link rel="stylesheet" href="{% static 'dashboard/css/vertical-layout-light/style.css' %}">
<!-- Aggiungere stili personalizzati per la pagina -->
<style>
    .profile-header {
        background-color: #f8f9fa;
        padding: 5px;
        border-radius: 8px;
        box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.1);
        text-align: center;
    }

    .profile-header img {
        /*width: 120px;
        height: 120px;
        margin-bottom: 15px;*/
        object-fit: cover;
        border-radius: 50%;
    }

    .section-title {
        font-weight: bold;
        color: #2d3e50;
        margin-top: 20px;
        border-bottom: 2px solid #ddd;
        padding-bottom: 10px;
    }

    .profile-stat {
        font-size: 24px;
        font-weight: bold;
    }

    .profile-stat-value {
        font-size: 18px;
        color: #28a745;
    }

    .card {
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
    }

    .card-body {
        padding: 20px;
    }

    .form-group {
        margin-bottom: 1rem;
    }

    .btn-custom {
        background-color: #0062cc;
        color: white;
        border: none;
    }

    .btn-custom:hover {
        background-color: #0056b3;
    }

    .form-control {
        border-radius: 5px;
    }

    .copy-link-btn {
        margin-top: 10px;
        background-color: #28a745;
        color: white;
        border: none;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">

    <!-- Header Profilo -->
    <div class="row mt-3">
        <div class="col-md-12">
            <img src="{{ user.profile.avatar.url }}" alt="Avatar" class="img-fluid rounded-circle">
            <h2>{{ user.first_name|default:"Guest" }} {{ user.last_name|default:"" }}</h2>
            <p class="text-muted">Benvenuto nel tuo profilo. Gestisci il tuo account e visualizza i tuoi referral.</p>
            <p>Ti sei registrato con il codice referral:
                {% if referrer_code %}
                {{ referrer_code }}
                {% else %}
                Nessuno
                {% endif %} </p>

            <h4>Il tuo codice referral</h4>
            {% if referral_code %}
            <div class="input-group">
                <input type="text" class="form-control" value="{{ referral_code }}" readonly>
                <button class="btn btn-primary" id="copy-code">Copia Codice</button>
            </div>
            {% else %}
            <p class="text-muted">Non hai un codice referral disponibile.</p>
            {% endif %}

        </div>
    </div>

    {% if messages %}
    <div class="alert alert-dismissible fade show mt-3">
        {% for message in messages %}
        <div class="alert {{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <!-- Modifica Dati Personali -->
    <div class="row mt-3">
        <div class="col-md-12">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h4 class="section-title mb-4">Modifica Dati Personali</h4>
                    <form method="POST" action="{% url 'core_profile' %}" enctype="multipart/form-data">
                        {% csrf_token %}

                        <!-- User form -->
                        {{ form.as_p }}

                        <!-- Profile form -->
                        {{ profile_form.as_p }}

                        <!-- Profile Base form -->
                        {{ profile_base_form.as_p }}

                        <!-- Profile Business form -->
                        {#{ profile_business_form.as_p }#}

                        <!-- Pulsanti -->
                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-primary btn-lg me-2">Salva Modifiche</button>
                            <button type="reset" class="btn btn-secondary btn-lg">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modifica Dati Personali -->
    <!--<div class="row mt-2">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="section-title">Modifica Dati Personali</h4>
                    <form method="post" action="{#% url 'profiles' %#}" enctype="multipart/form-data">
                        {#% csrf_token %#}
                        <div class="form-group">
                            <label for="id_username">Username:</label>
                            <input type="text" value="{#{ user.username }#}">
                        </div>
                        <div class="form-group">
                            <label for="id_first_name">Nome:</label>
                            <input type="text" value="{##{ user.first_name }##}">
                        </div>
                        <div class="form-group">
                            <label for="id_last_name">Cognome:</label>
                            <input type="text" value="{##{ user.last_name }##}">
                        </div>
                        <div class="form-group">
                            <label for="id_email">Email:</label>
                            <input type="text" value="{#{ user.email }#}">
                        </div>
                        <div class="form-group">
                            <label for="id_bio">Bio:</label>
                            <input type="text" value="{#{ user.bio }#}">
                        </div>
                        <div class="form-group">
                            <label for="id_avatar">Cambia Avatar:</label>
                            {#{ profile_form.avatar }#}
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-custom btn-lg">Salva Modifiche</button>
                            <button type="reset" class="btn btn-secondary btn-lg">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>-->

</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'dashboard/vendors/js/vendor.bundle.base.js' %}"></script>
<script src="{% static 'dashboard/js/off-canvas.js' %}"></script>
<script src="{% static 'dashboard/js/hoverable-collapse.js' %}"></script>
<script src="{% static 'dashboard/js/template.js' %}"></script>
<script src="{% static 'dashboard/js/settings.js' %}"></script>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {
        // Funzione per copiare il link referral
        $('#copy-code').click(function () {
            var referralLink = $('#referral-link');
            referralLink.select();
            document.execCommand('copy');
            alert('Link Referral Copiato!');
        });

        // Funzione per copiare il link referral
        $('#copy-code').click(function () {
            var copyText = $('#referral-link')[0];
            copyText.select();
            document.execCommand('copy');
            alert('Link referral copiato!');
        });

        // Carica i dati relativi ai referral
        /*function loadProfileData() {
            $.ajax({
                url: '{% url "core_profile_data" %}', // URL per l'API
                method: 'GET',
                success: function (response) {
                    // Aggiorna i dati nel template
                    $('#total-commission').text(`€${response.referral_data.total_commission}`);
                    $('#active-referrals').text(response.referral_data.active_referrals);
                    $('#total-rewards').text(`€${response.referral_data.total_rewards}`);
                    $('#bonus-amount').text(`€${response.referral_bonus}`);
                    $('#bonus-programs-count').text(response.referral_bonus_programs?.length);
                    $('#referral-codes-count').text(response.referral_codes?.length);
                    $('#active-referral-codes').text(response.active_referral_codes?.length);

                    // Attività recenti
                    let activityHtml = '';
                    if (Array.isArray(recent_activities)) {
                        response.recent_activities.forEach(function (activity) {
                            activityHtml += `<tr>
                        <td>${new Date(activity.date).toLocaleDateString()}</td>
                        <td>${activity.type}</td>
                        <td>${activity.details}</td>
                        <td>€${activity.amount}</td>
                    </tr>`;
                        });
                        $('#recent-activities tbody').html(activityHtml);
                    }
                },
                error: function (error) {
                    console.error('Error loading profile data:', error);
                }
            });
        }*/


        // Funzione per caricare i dati dalla backend
        function loadUserData() {
            const response = fetch('http://localhost:8000/get-level-users/');  // URL delle API backend
            const users = response.json();

            console.log(users);
            let tableBody = document.getElementById('user-table-tbody');
            tableBody.innerHTML = '';  // Svuota la tabella esistente

            // Aggiungi una riga per ogni utente
            users.forEach(user => {
                const row = document.createElement('tr');

                row.innerHTML = `
                    <td>${user.first_name}</td>
                    <td>${user.last_name}</td>
                    <td>${user.username}</td>
                    <td>${user.level}</td>
                `;

                console.log(row);
                tableBody.appendChild(row);
            });
        }

        // Carica i dati degli utenti quando la pagina viene caricata
        //loadUserData(); // document.addEventListener('DOMContentLoaded', loadUserData);
        // Carica i dati all'avvio
        // loadProfileData();
    });
</script>
{% endblock %}